#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\saiki\OneDrive\Desktop\Nagraju annaya\telugupython\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\saiki\OneDrive\Desktop\Nagraju annaya\telugupython\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\saiki\OneDrive\Desktop\Nagraju annaya\telugupython\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\saiki\OneDrive\Desktop\Nagraju annaya\telugupython\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\saiki\OneDrive\Desktop\Nagraju annaya\telugupython\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd 

data = [1,2,3,4,5]
series = pd.Series(data)
print("series \n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## create a series from dict 

data = {'a':1,'b':2,'c':3}

series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
## data frames


data = {
    'Name':['Roshan babu','attitude star','kaysidhu'],
    'age':[26,28,27],
    'city':['Blr','hyd','chennai']
}

In [10]:
df= pd.DataFrame(data)

In [13]:
df
print(df)

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [11]:
df

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [14]:
print(type(df))

<class 'pandas.DataFrame'>

In [ ]:
sales_data = pd.read_csv('sales_data.csv')

In [20]:
sales_data.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [22]:
sales_data.tail(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
230,10231,2024-08-18,Clothing,Adidas Originals Trefoil Hoodie,4,64.99,259.96,Asia,Debit Card
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card
232,10233,2024-08-20,Beauty Products,Fresh Sugar Lip Treatment,1,24.00,24.00,Europe,PayPal
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [23]:
df

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [24]:
df['Name']

0      Roshan babu
1    attitude star
2         kaysidhu
Name: Name, dtype: str

In [25]:
df.loc[0]

Name    Roshan babu
age              26
city            Blr
Name: 0, dtype: object

In [26]:
df.iloc[0]

Name    Roshan babu
age              26
city            Blr
Name: 0, dtype: object

In [27]:
df

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [29]:
print(df.at[1,'age'])

28

In [30]:
print(df.at[0,'Name'])

Roshan babu

In [31]:
df

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [32]:
df['Fanbse']=[50000,60000,76000]

In [33]:
df

            Name  age     city  Fanbse
0    Roshan babu   26      Blr   50000
1  attitude star   28      hyd   60000
2       kaysidhu   27  chennai   76000

In [41]:
##remove a column

df.drop('Fanbse',axis= 1,inplace=True)

In [42]:
df

            Name  age     city
0    Roshan babu   26      Blr
1  attitude star   28      hyd
2       kaysidhu   27  chennai

In [44]:
sales_data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [45]:
# Display the data types of each column
print("Data types:\n", sales_data.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", sales_data.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [46]:
sales_data.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000